# Generated by Django 4.1.2 on 2022-10-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_account_amenity_gym_staff_membership_gym_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_classes',
        ),
        migrations.RemoveField(
            model_name='class',
            name='staff',
        ),
        migrations.AddField(
            model_name='class',
            name='staff',
            field=models.ManyToManyField(to='management.staff'),
        ),
    ]
